server:
 servlet:
  context-path:
 port: 8089

cupSize: C 
name: \u738B\u7F8E\u4E3D 
age: 20 

content: "name: ${name} age: ${age} cupSize: ${cupSize0}" 

girl:
 name: \u6797\u5FD7\u73B2 
 age: 55 
 cupsize: f 

filepath:
 qrFile: E:\\files\\ZhbQr 